#服务器端口
server:
  port: 8200

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

logging:
  level:
    ROOT: error
  file: logs/openapi-isv.log
